export const config = {
  port: Number(process.env.PORT) || 3000,
  toolCallTimeoutMs: Number(process.env.TOOL_CALL_TIMEOUT_MS) || 30_000,
  healthCheckTimeoutMs: Number(process.env.HEALTH_CHECK_TIMEOUT_MS) || 5_000,
  healthCheckIntervalMs: Number(process.env.HEALTH_CHECK_INTERVAL_MS) || 30_000,
  openapiDiscoveryTimeoutMs: Number(process.env.OPENAPI_DISCOVERY_TIMEOUT_MS) || 10_000,
  sessionTtlMs: Number(process.env.SESSION_TTL_MS) || 1_800_000,
  maxSessions: Number(process.env.MAX_SESSIONS) || 100,
  allowPrivateIps: process.env.ALLOW_PRIVATE_IPS === "true",
  allowedHosts: process.env.ALLOWED_HOSTS?.split(",").map(h => h.trim()).filter(Boolean) ?? [],
  allowedOrigins: process.env.ALLOWED_ORIGINS?.split(",").map(o => o.trim()).filter(Boolean) ?? ["http://localhost:*"],
  corsOrigins: process.env.CORS_ORIGINS?.split(",").map(o => o.trim()).filter(Boolean) ?? [],
  authDisabled: process.env.AUTH_DISABLED === "true",
  adminApiKeys: process.env.ADMIN_API_KEYS?.split(",").map(k => k.trim()).filter(Boolean) ?? [],
  mcpApiKeys: process.env.MCP_API_KEYS?.split(",").map(k => k.trim()).filter(Boolean) ?? [],
  rateLimitRegister: Number(process.env.RATE_LIMIT_REGISTER) || 10,
  rateLimitMcp: Number(process.env.RATE_LIMIT_MCP) || 100,
  rateLimitGlobal: Number(process.env.RATE_LIMIT_GLOBAL) || 1000,
  logFormat: (process.env.LOG_FORMAT as "json" | "text") || "json",
  maxConsecutiveFailures: Number(process.env.MAX_CONSECUTIVE_FAILURES) || 10,
  trustProxy: process.env.TRUST_PROXY === "true" ? true : (Number(process.env.TRUST_PROXY) || false),
};
